### ISSUE TITLE
Integration in LazyPig

### ISSUE THREAD

**Issue by FrostShock** [shirsig/retarget#6]
Hi, I tried to integrate Retarget into LazyPig. I am not sure yet if it's working or not, I still have to meet a hunter or rogue of opposing faction - https://github.com/FrostShock/LazyPig
I hope you don't mind that.

If you want and have time, please take a look at it, maybe you can optimize the integration

Thanks for this great addon!

**Comment by shirsig** [comment]
Hey, not at all, feel free to use it. 
It looks like it will work like this. To be safe you may wanna wrap it inside a do/end block to make sure the local variables won't conflict with others in the same file.
